export default{
    namespaced:true,
    state:{
        thingsTwo2: [
            {
                src: require('../assets/images/g3.jpg'),
                title: '唯他可可 椰子水饮料 330毫升/盒 12盒',
                price1: 19.9,
                price2: 29.9,
                collection:0,
                id:1,
                status:false,
            },
            {
                src: require('../assets/images/meitu5.jpg'),
                title: '巴黎水 含气青柠味饮料 330毫升 24',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id:2,
                status: false,
            },
            {
                src: require('../assets/images/meitu6.jpg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id:3,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id:4,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 5,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 6,
                status: false,
            },
        ],
        thingsTwo3: [
            {
                src: require('../assets/images/xihu0.jpg'),
                title: '唯他可可 椰子水饮料 330毫升/盒 12盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 1,
                status: false,
            }, {
                src: require('../assets/images/xihu02.png'),
                title: '巴黎水 含气青柠味饮料 330毫升 24',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 2,
                status: false,
            }, {
                src: require('../assets/images/gallery-3.jpg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 3,
                status: false,
            }, {
                src: require('../assets/images/xihu03.jpg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 4,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 5,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 6,
                status: false,
            },
        ],
        thingsTwo4: [
            {
                src: require('../assets/images/lifu01.webp'),
                title: '唯他可可 椰子水饮料 330毫升/盒 12盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 1,
                status: false,
            }, {
                src: require('../assets/images/lifu02.webp'),
                title: '巴黎水 含气青柠味饮料 330毫升 24',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 2,
                status: false,
            }, {
                src: require('../assets/images/lifu03.webp'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 3,
                status: false,
            }, {
                src: require('../assets/images/lifu04.webp'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 4,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 5,
                status: false,
            }, {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 6,
                status: false,
            },
        ],
        thingsTwo5: [
            {
                src: require('../assets/images/buzhi01.webp'),
                title: '唯他可可 椰子水饮料 330毫升/盒 12盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 1,
                status: false,
            }, {
                src: require('../assets/images/buzhi02.webp'),
                title: '巴黎水 含气青柠味饮料 330毫升 24',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 2,
                status: false,
            }, {
                src: require('../assets/images/buzhi03.webp'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 3,
                status: false,
            }, {
                src: require('../assets/images/buzhi04.webp'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 4,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 5,
                status: false,
            }, {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 6,
                status: false,
            },
        ],
        youlike: [
            {
                src: require('../assets/images/gallery-1.jpg'),
                title: '唯他可可 椰子水饮料 330毫升/盒 12盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 1,
                status: false,
            }, {
                src: require('../assets/images/gallery-2.jpg'),
                title: '巴黎水 含气青柠味饮料 330毫升 24',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 2,
                status: false,
            }, {
                src: require('../assets/images/gallery-3.jpg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 3,
                status: false,
            }, {
                src: require('../assets/images/gallery-4.jpg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 4,
                status: false,
            },
            {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 5,
                status: false,
            }, {
                src: require('../assets/images/meitu7.jpeg'),
                title: 'calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒',
                price1: 19.9,
                price2: 29.9,
                collection: 0,
                id: 6,
                status: false,
            },
        ],
    },
    mutations: {
        edit(state,obj){
            let index = state.thingsTwo2.findIndex(item=>item.id==obj.id);
            state.thingsTwo2[index].status = obj.status;
        },
    }
}